#
# osmconf for inland water polygon extraction (rivers + ponds).
# Based on GDAL's default, with waterway/water promoted to columns.
#
[general]
closed_ways_are_polygons=aeroway,amenity,boundary,building,craft,geological,historic,landuse,leisure,military,natural,office,place,shop,sport,tourism,waterway=riverbank,waterway=river,highway=platform,public_transport=platform
tags_format=json

[points]
osm_id=yes
attributes=name
other_tags=no

[lines]
osm_id=yes
attributes=name,waterway
other_tags=no

[multipolygons]
osm_id=yes
attributes=name,type,natural,landuse,waterway,water,wetland
ignore=area,created_by,converted_by,source,time,ele,note,todo,openGeoDB:,fixme,FIXME
other_tags=no

[multilinestrings]
osm_id=yes
attributes=name,type
other_tags=no

[other_relations]
osm_id=yes
attributes=name,type
other_tags=no
